import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { ensureUserRecord } from '@/lib/users';
import { z } from 'zod';
import { getAuthSession } from '@/lib/auth';

const progressSchema = z.object({
  lessonId: z.string(),
  completed: z.boolean().optional().default(true),
});

export async function POST(request: Request) {
  try {
    const session = await getAuthSession();
    if (!session.isAuthenticated || !session.userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    const { lessonId, completed } = progressSchema.parse(body);

    const user = await ensureUserRecord(session.userId);

    // Get lesson and verify enrollment
    const lesson = await prisma.lesson.findUnique({
      where: { id: lessonId },
      include: {
        module: {
          include: {
            course: true,
          },
        },
      },
    });

    if (!lesson) {
      return NextResponse.json({ error: 'Lesson not found' }, { status: 404 });
    }

    // Check enrollment
    const enrollment = await prisma.enrollment.findUnique({
      where: {
        userId_courseId: {
          userId: user.id,
          courseId: lesson.module.course.id,
        },
      },
    });

    if (!enrollment) {
      return NextResponse.json({ error: 'Not enrolled in this course' }, { status: 403 });
    }

    // Update or create progress
    const progress = await prisma.progress.upsert({
      where: {
        userId_lessonId: {
          userId: user.id,
          lessonId: lesson.id,
        },
      },
      create: {
        userId: user.id,
        lessonId: lesson.id,
        completed,
        lastViewedAt: new Date(),
      },
      update: {
        completed,
        lastViewedAt: new Date(),
      },
    });

    // Check if course is complete and issue certificate
    if (completed) {
      await checkAndIssueCertificate(user.id, lesson.module.course.id);
    }

    return NextResponse.json({ success: true, progress }, { status: 200 });
  } catch (error) {
    if (error instanceof z.ZodError) {
      return NextResponse.json({ error: 'Invalid request', details: error.errors }, { status: 400 });
    }

    console.error('Progress update error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

async function checkAndIssueCertificate(userId: string, courseId: string) {
  // Get all lessons in course
  const course = await prisma.course.findUnique({
    where: { id: courseId },
    include: {
      modules: {
        include: {
          lessons: true,
        },
      },
    },
  });

  if (!course) return;

  const allLessons = course.modules.flatMap((m: any) => m.lessons);
  const totalLessons = allLessons.length;

  // Get completed lessons
  const completedProgress = await prisma.progress.findMany({
    where: {
      userId,
      lessonId: { in: allLessons.map((l: any) => l.id) },
      completed: true,
    },
  });

  // If all lessons complete, issue certificate
  if (completedProgress.length === totalLessons) {
    const existingCertificate = await prisma.certificate.findUnique({
      where: {
        userId_courseId: {
          userId,
          courseId,
        },
      },
    });

    if (!existingCertificate) {
      const certificate = await prisma.certificate.create({
        data: {
          userId,
          courseId,
          // PDF URL will be generated by certificate route
        },
      });

      // Send certificate email
      const user = await prisma.user.findUnique({ where: { id: userId } });
      if (user) {
        const { sendCertificateEmail } = await import('@/lib/email');
        const certificateUrl = `${process.env.NEXT_PUBLIC_APP_URL}/certificate/${certificate.id}`;
        await sendCertificateEmail(user.email, course.title, certificateUrl, user.name || 'Learner');
      }
    }
  }
}
